version: '3'
services:
    db:
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: jenjul
            POSTGRES_DB: fastapi
        ports:
            - 5432:5432

    api:
        build: .
        depends_on:
            - db
        ports:
            - 8000:8000
        env_file:
            - .env
        volumes:
            - .:/app
        command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
        