name: Build and Deploy code
# Trigger the workflow on every push/pull_request
on: [push,pull_request] 

jobs: 
  build-test-deploy:
    environment:
      name: testing
    env:
      DATABASE_HOSTNAME: ${{secrets.DATABASE_HOSTNAME}}
      DATABASE_PORT: ${{secrets.DATABASE_PORT}}
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
      DATABASE_NAME: ${{secrets.DATABASE_NAME}}
      DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      ALGORITHM: ${{secrets.ALGORITHM}}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{secrets.ACCESS_TOKEN_EXPIRE_MINUTES}}

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: 

    runs-on: ubuntu-latest
    steps:
      # Step 1: Get the code
      - name: checkout code
        uses: actions/checkout@v3
      
      # Step 2: Install Python dependencies
      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: Install Dependencies
        run: pip install -r requirements.txt

      # Step 3: Run tests,| to run multiple install
      - name: Run tests
        run: |
          pip install pytest
          pytest
